version: "3.3"

services:
  mysql:
    image: mariadb:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRoot123
      MYSQL_DATABASE: cloud_computing
      MYSQL_USER: php
      MYSQL_PASSWORD: php
    networks:
      - mynet

  myredis:
    image: redis:latest
    container_name: myredis
    networks:
      - mynet

  myphp:
    build:
      context: ./src/php
      dockerfile: Dockerfile
    container_name: myphp
    ports:
      - "9000:9000"
    volumes:
      - ./src:/var/www/html
    networks:
      - mynet
    depends_on:
      - mysql
      - myredis
 
  mynginx:
    image: nginx:latest
    container_name: mynginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./src/nginx.ini:/etc/nginx/conf.d/default.conf
    networks:
      - mynet
    depends_on:
      - myphp

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: php
      PMA_PASSWORD: php
      MYSQL_ROOT_PASSWORD: MyDBRoot123 
    networks:
      - mynet
    depends_on:
      - mysql

networks:
  mynet:
    driver: bridge
